### 로그인
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "id": "user1@cawave.co.kr",
  "password": "qwe123!@#"
}

> {%
client.global.set("token", response.body.data)
%}

### 게시글 조회
GET http://localhost:8080/api/board
Authorization: Bearer {{token}}

### 게시글 상세조회
GET http://localhost:8080/api/board/1
Authorization: Bearer {{token}}

### 게시글 생성
POST http://localhost:8080/api/board
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Board 1",
  "content": "Board 1 content"
}

### 게시글 수정
PATCH http://localhost:8080/api/board/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Board 2",
  "content": "Board 2 content update"
}

### 게시글 삭제
DELETE http://localhost:8080/api/board/1
Authorization: Bearer {{token}}

### 댓글 조회
GET http://localhost:8080/api/comment?boardId=1
Authorization: Bearer {{token}}

### 댓글 생성
POST http://localhost:8080/api/comment
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "boardId": 1,
    "content": "Board1 Comment 33"
}

### 댓글 수정
PATCH http://localhost:8080/api/comment/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "Comment 2 update"
}

### 댓글 삭제
DELETE http://localhost:8080/api/comment/3
Authorization: Bearer {{token}}