= Spring REST Docs[Billing]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: 요청 예시
:operation-path-parameters-title: 경로 변수
:operation-query-parameters-title: 쿼리 변수
:operation-request-fields-title: 요청 본문
:operation-request-parts-title: 요청 본문
:operation-http-response-title: 응답 예시
:operation-response-body-title: 응답 본문
:operation-response-fields-title: 응답 본문
:operation-response-fields-data-title: 응답 본문
:operation-common-httpstatus-code-title: Common Status


[[board-list]]
=== 게시판 목록조회

operation::board-controller-test/get-boards[snippets='http-request,query-parameters,http-response,response-fields-data']


[[board-get]]
=== 게시판 조회

operation::board-controller-test/get-board[snippets='http-request,path-parameters,http-response,response-fields-data']


[[board-create]]
=== 게시판 생성

operation::board-controller-test/create-board[snippets='http-request,request-fields,http-response,response-fields']

[[board-update]]
=== 게시판 수정

operation::board-controller-test/update-board[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[board-delete]]
=== 게시판 삭제

operation::board-controller-test/delete-board[snippets='http-request,path-parameters,http-response']



[[comment-list]]
=== 댓글 목록조회

operation::comment-controller-test/get-comments[snippets='http-request,query-parameters,http-response,response-fields-data']


[[comment-create]]
=== 댓글 생성

operation::comment-controller-test/create-comment[snippets='http-request,request-fields,http-response,response-fields']

[[comment-update]]
=== 댓글 수정

operation::comment-controller-test/update-comment[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[comment-delete]]
=== 댓글 삭제

operation::comment-controller-test/delete-comment[snippets='http-request,path-parameters,http-response']